spring:
  application:
    name: core
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_AUTH_URL}
server:
  port: ${SERVER_PORT}
paladin:
  security:
    jwt-secret-key: ${JWT_SECRET_KEY}