spring:
  application:
    name: core
  datasource:
    url: ${POSTGRES_DB_JDBC}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: ${paladin.include-stack-trace}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_AUTH_URL}
server:
  port: ${SERVER_PORT}
paladin:
  security:
    jwt-secret-key: ${JWT_SECRET_KEY}
    jwt-issuer: ${JWT_ISSUER}
    allowed-origins:
      - ${ORIGIN_API_URL}
  include-stack-trace: true
  standalone: false
  require-data-encryption: true
springdoc:
  api-docs:
    path: /docs/v3/api-docs
  swagger-ui:
    path: /docs/swagger-ui.html